name: Code Review with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install openai

    - name: Run code review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: node .github/scripts/code_review.js
